require: rubocop-rails

AllCops:
  # 除外するディレクトリ（自動生成されるファイル）
  # 제외할 디렉터리(자동 생성되는 파일)
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"

  # 新ルールを有効化
  # 새 규칙 유효화(활성화)
  NewCops: enable

# 1行あたりの文字数をチェックする
# 한 행당 문자 수 검사
Layout/LineLength:
  Max: 130
  # 下記ファイルはチェックの対象から外す
  # 하기 파일은 체크 대상에서 제외
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

# RSpecは1つのブロックあたりの行数が多くなるため、チェックの除外から外す
# ブロック内の行数をチェックする
# RSpec은 하나의 블록당 행 수가 많아지므로, 체크 제외에서 제외
# 블록 내 행수를 체크
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

# Assignment: 変数への代入
# Branch: メソッド呼び出し
# Condition: 条件文
# 上記項目をRubocopが計算して基準値を超えると警告を出す（上記頭文字をとって'Abc'）
# Assignment: 변수에 대입
# Branch: 메서드 호출
# Condition: 조건문
# 상기 항목을 Rubocop이 계산해서 기준값을 초과하면 경고 출력(상기 머리 문자를 따서 'Abc')
Metrics/AbcSize:
  Max: 50

# メソッドの中身が複雑になっていないか、Rubocopが計算して基準値を超えると警告を出す
# 메서드 내용이 복잡해지지 않았는지, Rubocop가 계산하여 기준값을 넘으면 경고 출력
Metrics/PerceivedComplexity:
  Max: 8

# 循環的複雑度が高すぎないかをチェック（ifやforなどを1メソッド内で使いすぎている）
# 순환적 복잡도가 지나치게 높지 않은지 체크(if나 for 등을 한 메서드 내에서 지나치게 사용 중)
Metrics/CyclomaticComplexity:
  Max: 10

# メソッドの行数が多すぎないかをチェック
# 메서드의 행 수가 지나치게 많지 않은지 체크
Metrics/MethodLength:
  Max: 30

# ネストが深すぎないかをチェック（if文のネストもチェック）
# 네스트(중첩)이 지나치게 깊지 않은지 체크(if문의 중첩도 체크)
Metrics/BlockNesting:
  Max: 5

# クラスの行数をチェック（無効）
# 클래스의 행수 체크(무효, 비활성화)
Metrics/ClassLength:
  Enabled: false

# 空メソッドの場合に、1行のスタイルにしない　NG例：def style1; end
# 빈 메서드일 경우, 한 행 스타일로 하지 않음
# NG 예: def style1; end
Style/EmptyMethod:
  EnforcedStyle: expanded

# クラス内にクラスが定義されていないかチェック（無効）
# 클래스 내에 클래스가 정의되어 있지 않은지 체크(무효)
Style/ClassAndModuleChildren:
  Enabled: false

# 日本語でのコメントを許可
# 일본어 주석 허가
Style/AsciiComments:
  Enabled: false

# クラスやモジュール定義前に、それらの説明書きがあるかをチェック（無効）
# 클래스나 모듈 정의 전에 설명이 있는지를 체크(무효)
Style/Documentation:
  Enabled: false

# ％i（）構文を使用していないシンボルで構成される配列リテラルをチェック（無効）
# %i() 구문을 사용하지 않은 심볼로 구성된 배열 리터럴 체크(무효)
Style/SymbolArray:
  Enabled: false

# 文字列に値が代入されて変わっていないかチェック（無効）
# 문자열에 값이 대입되어 변경되지 않았는지 체크(무효)
Style/FrozenStringLiteralComment:
  Enabled: false

# メソッドパラメータ名の最小文字数を設定
# 메서드 파라미터명의 최소 문자 수 설정
Naming/MethodParameterName:
  MinNameLength: 1
